Minor fixes
GMPavanLab/dynsight pull request #31
Opened 2024-09-09 13:10 UTC by SimoneMartino98

Hi everybody;
In order to solve some minor issues I made this pull request that contain some changes. 

### Solved #8 
Added DEV installation part to the README; @andrewtarzia if you want to check this part because it is the only part that I wrote by myself.

### Solved #14 
Changed the sentence in the ``onion-clustering`` docs part according to the one suggested by @matteobecchi (let me know if it is ok, I've simply copied and pasted it).

### Solved #30 
Added ``onion-clustering`` to the group of Dynsight public dependencies and removed it from the DEV ones. Now Onion should be installed during the Dynsight installation procedure (``pip install dynsight``).

### New mainteiners
Added me and @matteobecchi as new maintainers, with @andrewtarzia, of the Dynsight project (in both README.rst and pyproject.toml).

After that new pull requests will follow with other bigger updates.
thank you

2024-09-09 13:51 UTC, andrewtarzia requested changes

2024-09-09 13:51 UTC, andrewtarzia commented on README.rst
> +DEV installation
Make it "Developer Setup"

2024-09-09 13:51 UTC, andrewtarzia commented on README.rst
> +============
Make sure the "=" line always matches the length of the title above it.

2024-09-09 13:51 UTC, andrewtarzia commented on README.rst
> +If you want to setup a development version of ``dynsight`` you can follow this simple steps:
Remove this line, and just have the numbered list.

2024-09-09 13:51 UTC, andrewtarzia commented on README.rst
> +
Maybe change the above to something like (my rationale is that you do not need to tell people how to clone a repository):

```
#. Install `just`_.
#. Fork the ``dynsight`` repository
#. In a new virtual environment run using Python 3.10::

    $ just dev

#. Run code checks::

    $ just check
  


.. _`just`: https://github.com/casey/just
```

2024-09-09 14:59 UTC, SimoneMartino98 commented
All requests should be made. Let me know if there are any other changes.

2024-09-09 15:05 UTC, andrewtarzia commented on README.rst
> +
Check formatting.

2024-09-10 07:34 UTC, matteobecchi approved these changes
Changes regarding the onion pytest are OK!

2024-09-10 07:37 UTC, matteobecchi commented on docs/source/onion.rst
> +The code for performing clustering on multi time-series can be found in ``examples/onion_multi.py``. The only differences that the input file has to be an .npy or .npz containing a numpy.ndarray with
Should it be "The only difference is that" instead of "The only differences that"?

2024-09-10 07:51 UTC, merged