Spatial smoothing algorithm in Dynsight
GMPavanLab/dynsight pull request #32
Opened 2024-09-12 12:34 UTC by SimoneMartino98

With this pull request I want to add the spatial smoothing parallelized algorithm.

In brief, this code can be useful when the user wants to average the value of a collective variable of a particle with the values of its neighboring particles, defined by a cutoff distance.

2024-09-12 14:34 UTC, andrewtarzia commented on src/dynsight/_internal/data_processing/spatial_smoothing.py
> +    # The mypy error [call-overload] is ignored as it is considered.
Remove the full stop at the end.

Also, a bit more detail is needed: `np.frombuffer type is 'buffer-like', which contains 'Array'`

2024-09-20 13:08 UTC, andrewtarzia requested changes

2024-09-20 13:48 UTC, SimoneMartino98 commented on docs/source/data_processing.rst
> +Pre-analysis tools
done

2024-09-20 13:53 UTC, SimoneMartino98 commented on src/dynsight/_internal/data_processing/spatial_average.py
> +        selection.positions, selection.positions, box=universe.dimensions
done

2024-09-20 14:31 UTC, SimoneMartino98 commented on src/dynsight/_internal/data_processing/spatial_average.py
> +                                universe = u,
only in the docs or in the entire code ?

2024-09-20 15:51 UTC, andrewtarzia commented on src/dynsight/_internal/data_processing/spatial_average.py
> +                                universe = u,
Only when it is for a keyword argument, like in this line of code

2024-09-20 16:02 UTC, SimoneMartino98 commented on src/dynsight/_internal/data_processing/spatial_average.py
> +                                universe = u,
ok; I'll do it

2024-09-20 18:43 UTC, andrewtarzia commented on src/dynsight/_internal/data_processing/spatial_average.py
> +    shared_array: np.ndarray[float, Any], shape: int, dtype: tuple[float, Any]
bring `shape` to the next line.

2024-09-20 18:47 UTC, andrewtarzia commented on src/dynsight/_internal/data_processing/spatial_average.py
> +        np.ndarray
Remove this typing.

2024-09-20 18:48 UTC, andrewtarzia commented
Almost there, a few unresolved conversations above.

2024-09-23 14:08 UTC, andrewtarzia commented on src/dynsight/_internal/data_processing/spatial_average.py
>              Path to the file containing the NumPy array of descriptor values.
Minor fix.

2024-09-23 14:09 UTC, andrewtarzia approved these changes

2024-09-23 14:42 UTC, merged